services:
  - name: "ControlerService"
    host: "http://localhost"
    port: 8080
  - name: "OrderService"
    host: "http://localhost"
    port: 8081
  - name: "InventoryService"
    host: "http://localhost"
    port: 8082
  - name: "CatalogService"
    host: "http://localhost"
    port: 8083
inventory:
  maxItems: 100
  maxItemQuantity: 10000
customer:
  maxCustomers: 1
  itemsPerOrder: 5
  quantityPerItem: 1
