services:
  - name: "ControlerService"
    host: "localhost"
    port: 8080
  - name: "OrderService"
    host: "localhost"
    port: 8081
  - name: "InventoryService"
    host: "localhost"
    port: 8082
  - name: "CatalogService"
    host: "localhost"
    port: 8083
inventory:
  maxItems: 100
  maxItemQuantity: 10000
