services:
  - name: "OrderService"
    host: "localhost"
    port: 8080
  - name: "InventoryService"
    host: "localhost"
    port: 8081
  - name: "AccountService"
    host: "localhost"
    port: 8082
